trypear/pearai-submodule

package.json
=> PearAI show up in command palette

lib/webview/project.json, package.json, pnpm-lock.yaml
This pull request addresses problems related to the handling of environment variables in project files. The `cross-env` package has been added as a dev dependency, which is utilized during the build process. It enables setting variables at the project's root just before executing `nx` commands. Additionally, it can be used within specific projects by adding custom scripts.
By incorporating `cross-env`, this change enhances visibility and minimizes errors commonly encountered when managing environment variables across the project.
=> Use cross-env package to manage build env variables

scripts/build-extension.sh
Pretty sure this is all thats needed to build
=> Added build-extension

extensions/vscode/gui/index.html, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/pearai_tutorial.py
=> Merge conflicts. Running Windows

.github/CODEOWNERS, .github/workflows/assign-author.yml
Adds reviewers and assignees to each PR
=> Added github workflow to add relevant people to review

extensions/vscode/pearai_tutorial.py
Improved it.  it wasnt a strong enough walkthrough in continue's version imo
https://github.com/trypear/pearai-app/issues/130
=> Changed tutorial

extensions/vscode/pearai_tutorial.py, extensions/vscode/src/util/ideUtils.ts
Fixed the case where the last line is not a cmd prompt
=> Added cmd+shift+R edge cases

extensions/vscode/config_schema.json, gui/src/components/dialogs/FTCDialog.tsx, gui/src/util/modelData.ts
[ What changed? Feel free to be brief. ]
=> Added renames

docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/scripts/prepackage.js
Changed the serialized config name in `prepackage.js` as the properties field keeps returning as `undefined`
=> Change Serialized Config to `SerializedPearAIConfig`

core/llm/index.ts, extensions/vscode/src/webviewProtocol.ts
solves [#134](https://github.com/trypear/pearai-app/issues/134)
this pr dismisses the error message showing every time we open pearai app.
steps to get error: 
open pear ai app, first time you edit any file, the error will show up on UI, consecutively if you make more changes, the error still happens but does not appear on UI, but you can see error in developer tools.
Later we can remove this when we have free trial for pearAI.
=> chore: suppress unauth error for now

CONTRIBUTING.md, core/autocomplete/completionProvider.ts, core/indexing/docs/preIndexedDocs.ts, docs/docusaurus.config.js, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/intellij/src/main/resources/continue_tutorial.py, extensions/vscode/README.md, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/util/loadAutocompleteModel.ts, extensions/vscode/src/webviewProtocol.ts, gui/src/components/dialogs/FTCDialog.tsx, gui/src/components/dialogs/SetupLocalOrKey.tsx, gui/src/components/mainInput/getSuggestion.ts, gui/src/pages/help.tsx, gui/src/pages/migration.tsx, gui/src/pages/models.tsx, gui/src/pages/onboarding/onboarding.tsx
Renamed continue site to pearai site
Will have some 404's but its okay for now
=> Rename continue site to pearai site

core/db/token.ts, core/llm/llms/PearAIServer.ts, gui/src/pages/modelconfig.tsx
accessToken wasnt updating but now it is
=> Fixed accessToken updating bug

extensions/vscode/package.json, extensions/vscode/src/commands.ts, gui/src/hooks/useHistory.tsx, gui/src/pages/gui.tsx, gui/src/redux/slices/stateSlice.ts
Added a keyboard shortcut `CMD+0` to toggle between the last opened chat and the current chat.
=> Add CMD+0 shortcut to toggle between last opened and current chat

docs/docs/quickstart.md, extensions/vscode/src/webviewProtocol.ts, gui/src/components/dialogs/SetupLocalOrKey.tsx, gui/src/pages/gui.tsx, gui/src/redux/slices/serverStateReducer.ts
[ What changed? Feel free to be brief. ]
=> Renamed using continue

core/config/default.ts, extensions/vscode/src/commands.ts
=> Removed default free trials, and fixed localhost unintentionally in prod

gui/src/pages/modelconfig.tsx, gui/src/util/modelData.ts
Codebase got in an ugly state from merging this fixes it .
=> Added syntax fix for modelconfig

core/llm/llms/PearAIServer.ts, gui/src/pages/gui.tsx, gui/src/pages/modelconfig.tsx, gui/src/pages/models.tsx, gui/src/util/modelData.ts
#157 
https://github.com/trypear/pearai-app/issues/157
also fixes the PearAI option here:
=> Added default flow progress

binary/package-lock.json, core/config/load.ts, core/indexing/docs/crawl.ts, core/llm/index.ts, core/package-lock.json, docs/package-lock.json, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/autocomplete/lsp.ts, gui/package-lock.json, gui/src/components/mainInput/ContextItemsPeek.tsx
Below is a list of security concerns that have been addressed by this pr:
- https://github.com/trypear/pearai-submodule/security/dependabot/35
- https://github.com/trypear/pearai-submodule/security/dependabot/34
- https://github.com/trypear/pearai-submodule/security/dependabot/33
- https://github.com/trypear/pearai-submodule/security/dependabot/32
- https://github.com/trypear/pearai-submodule/security/dependabot/31
- https://github.com/trypear/pearai-submodule/security/dependabot/30
- https://github.com/trypear/pearai-submodule/security/dependabot/29
- https://github.com/trypear/pearai-submodule/security/dependabot/28
- https://github.com/trypear/pearai-submodule/security/dependabot/24
- https://github.com/trypear/pearai-submodule/security/dependabot/23
- …
=> PearAI Submodule Security Updates

core/llm/llms/PearAIServer.ts, extensions/vscode/media/welcome.md, extensions/vscode/pearai_tutorial.py, gui/src/pages/modelconfig.tsx
Before, the CMD+I edit command was not working if we used the pearAI server as the provider. This fixes it!
=> Added changes for /stream_complete on PearAIServer and added changes for onboarding

scripts/build-extension.sh
- use the tsc command defind in scripts in package.json, 
- run build script in `gui` folder, without this, when we run code.sh, we don't pick up the changes in gui folder.
=> update build script to use npm run tsc and npm run build

core/web/webviewProtocol.ts, extensions/vscode/src/commands.ts, gui/src/hooks/useHistory.tsx, gui/src/pages/gui.tsx, gui/src/pages/history.tsx, gui/src/redux/slices/stateSlice.ts
`CMD + 0`
`CTRL+0`
to open last chat session.
and move focus to chat input box, after loading.
=> feat: switch between current and last chat

extensions/vscode/package.json
Clarified the Walkthrough label.
Related to issue https://github.com/trypear/pearai-app/issues/182 in the pear-application
=> Renamed PearAI walkthrough, to fix confusing labels

gui/src/pages/gui.tsx
#trypear/pearai-app#190
What changed?
- make button stick
- add bgcolor and text color, used vscode variables, so it matches with themes.
=> sticky 'Cancel' button

extensions/vscode/src/autocomplete/completionProvider.ts
Copilot autocomplete feature working:
https://github.com/user-attachments/assets/5bda368e-f40b-4960-923d-cfeab23d6d81
Tested on Ollama, OpenAI GPT-3, and PearAI Server
=> Get copilot autocomplete working

README.md
[ What changed? Feel free to be brief. ]
The URL behind the contributing in read me
=> Update the submodule repo readme

extensions/vscode/package-lock.json, extensions/vscode/package.json
=> Bumped version to v0.0.2

CONTRIBUTING.md, README.md
[ What changed? Feel free to be brief. ]
The other one was pointing to the pear ai repo
=> New updated link

gui/src/components/Layout.tsx
=> Added Add selected

.vscode/tasks.json
https://github.com/trypear/pearai-app/issues/210
=> Added fix for pearai not found

.github/pull_request_template.md
Closes [#254](https://github.com/trypear/pearai-app/issues/254)
- includes issue #
- adds emojis
- adds description guide
- adds more self checks
=> docs: detailed pr template

core/llm/llms/PearAIServer.ts
=> Fixed <im_end> bug

.github/pull_request_template.md
Closes #
- replaced checklist point including 'preview' w/ a screenshot check if applicable
=> docs: replace checklist point 'preview' w/  a screenshot check

core/config/default.ts, core/llm/llms/PearAIServer.ts, extensions/vscode/src/copySettings.ts
=> Stopped pylance and liveserver extensions from being copied over

core/llm/autodetect.ts, core/llm/llms/PearAIServer.ts, extensions/vscode/manual-testing-sandbox/test.js, extensions/vscode/package.json, extensions/vscode/src/commands.ts, extensions/vscode/src/copySettings.ts, extensions/vscode/src/webviewProtocol.ts, gui/src/pages/gui.tsx
=> Added logout and error handling

core/llm/autodetect.ts, core/llm/llms/PearAIServer.ts
<im_start> bug was due to templating issue.
Object object bug was due to model supports images.
=> Fixed pearai-server and anthropic

gui/src/components/ShortcutContainer.tsx
Dynamic variable was not working.
Closes #xxx
=> Reduce shortcuts bar font size

core/config/default.ts, core/llm/autodetect.ts, core/llm/llms/PearAIServer.ts, core/util/parameters.ts, extensions/vscode/src/util/loadAutocompleteModel.ts, gui/src/pages/gui.tsx
=> Fixed continue generation

core/autocomplete/README.md, core/config/default.ts, extensions/vscode/src/copySettings.ts
=> Small fixes

core/db/token.ts
Closes   Remove hard coded supabase keys in submodule ( issue on trypear/pearai-server ) 
Eliminated the need for hard coding of the url and keys, and added function to call them from the server
=> Removed hard coded supabase keys

core/config/default.ts, core/llm/index.ts, core/llm/llms/PearAIServer.ts
=> Added token tracking

gui/src/pages/onboarding/Onboarding.tsx
=> Onboarding new

extensions/vscode/package-lock.json, extensions/vscode/package.json
=> Bump to v1.0.0

core/config/default.ts, extensions/vscode/src/copySettings.ts, gui/src/pages/AddNewModel/configs/models.ts, gui/src/pages/onboarding/Onboarding.tsx
=> Added default model changes

core/llm/llms/PearAIServer.ts
We need to make a fire blog post on how to self host this
=> FIM disabling

extensions/vscode/package.json, gui/src/components/ShortcutContainer.tsx
=> Changed viewHistory shortcut to Cmd+H

core/protocol/ideWebview.ts, extensions/vscode/src/extension/VsCodeMessenger.ts, gui/src/pages/help.tsx
wasnt working functionality wise before to login - fixed
can still be made to be prettier
=> Added help buttons

core/config/load.ts, extensions/vscode/src/ContinueGUIWebviewViewProvider.ts, extensions/vscode/src/commands.ts
This reverts commit 5b655ec996bdfdc94b08629f8b07f56dc13c10f5.
We still need this for next version
=> Revert "feat: Login Button (Status Bar) (#150)"

extensions/intellij/src/main/resources/META-INF/plugin.xml, extensions/vscode/package.json, gui/src/pages/gui.tsx
Reverts trypear/pearai-submodule#138
=> Revert "Switching keybinds for appending and creating new chats"

extensions/vscode/pearai_tutorial.py, gui/src/components/dialogs/KeyboardShortcuts.tsx, gui/src/pages/help.tsx
Closes #xxx
UI changes for the new help buttons. Made them all the same size, and adaptive to window width.
=> clean up help buttons, reflect keybind changes

extensions/vscode/media/welcome.md, gui/src/components/dialogs/KeyboardShortcuts.tsx
=> Added cmd H shortcut

core/config/load.ts, gui/src/components/modelSelection/ModelSelect.tsx
- Enforces default models from default.ts
- It is now impossible to delete default models from config.json
- UI tweaks to separate PearAI models from user models
=> feat: Enforce default models + UI tweaks

extensions/vscode/src/lang-server/codeLens/providers/TutorialCodeLensProvider.ts, extensions/vscode/src/webviewProtocol.ts
S/o @MaySoMusician for showing how to do this :D
=> Added tutorial fixes

core/config/load.ts, gui/src/components/modelSelection/ModelSelect.tsx
Reverts trypear/pearai-submodule#184
=> Revert "feat: Enforce default models + UI tweaks"

gui/src/pages/AddNewModel/ConfigureProvider.tsx
=> Added remove

core/config/default.ts, core/config/load.ts, core/config/promptFile.ts
Adds leetcode command. Built in command.
=> Added leetcode 

core/core.ts, core/llm/llms/PearAIServer.ts, core/protocol/core.ts, core/protocol/passThrough.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt, extensions/vscode/src/commands.ts
=> Added reset pearai credentials working

gui/src/pages/AddNewModel/configs/providers.ts
https://github.com/trypear/pearai-app/issues/332
=> Removed cont

core/llm/llms/Bedrock.ts
Closes https://github.com/trypear/pearai-app/issues/336 
- Adding a map to exclude system messages
=> Filtering out system messages from Bedrock

extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/package.json
=> Added v1.1.0

core/llm/llms/PearAIServer.ts, extensions/vscode/src/util/loadAutocompleteModel.ts
Closes 
https://github.com/trypear/pearai-app/issues/343
https://github.com/trypear/pearai-app/issues/337
=> Removed unnecessary warnings!

core/config/default.ts
=> Added more prompt for leetcode

core/config/default.ts
=> Added config changes

core/config/load.ts
This will allow everyone who has old configs to have changes to default config in the future! :D
=> Added add defaults to config

core/config/default.ts
=> Added sensei slash command (replaces beginner)

core/config/default.ts, core/config/types.ts, core/context/providers/BeginnerContextProvider.ts, core/context/providers/FileTreeContextProvider.ts, core/context/providers/index.ts, core/index.d.ts, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
Closes https://github.com/trypear/pearai-app/issues/321 (this should be a issue in pear-app)
- Created a new custom context provider called "BeginnerContextProvider".
- Implemented getContextItems method to return beginner-friendly instructions.
- Users can simply type "@Beginner" to activate this mode for their questions.
=> [PAUSED] feat: beginner context provider

extensions/vscode/src/extension/VsCodeMessenger.ts
=> Amend Error message for no file open

oss-contributor-stats/README.md, oss-contributor-stats/get_stats.sh, oss-contributor-stats/process_stats.py, oss-contributor-stats/stats.txt
E.g. result: Percentage of non-founder contributions in the last 200 days: 37.72%
Closes #xxx
=> Add folder to get OSS stats
