lib/extension/src/webview/WebviewContainer.ts

This makes running the extension work both internal (part of vscode fork) and external (standalone)

Added dynamic pathing for internal and external

---

app/vscode/package.json
lib/extension/package.json
lib/webview/package.json

Resolved an issue where workspace dependencies were incorrectly installed. Previously, dependencies were being installed using `*` instead of `workspace:*`, causing errors during the build process.
**Error fixed:** Dependencies were not correctly recognized and linked within the NX workspace, leading to inconsistent behavior and build failures.
This change ensures that all workspace dependencies are accurately referenced and installed as `workspace:*`.

Fix pnpm "missing dependency" error

---

lib/webview/asset/chat.css

Previously, the error message box in the chat window could overflow on smaller panel widths, causing an undesired horizontal scroll.
**Error Fixed:** The error message box was not properly contained within the parent element, leading to display issues and user interface inconsistencies on a smaller sidebar width. 
**Changes:** The CSS styling has been changed to ensure the error message box remains within the bounds of the parent element. Additionally, the retry button has been moved to the bottom-right of the error message for clarity.
**Visual Comparison:**
Before:
After:
The styling changes ensure that the error message is contained inside the parent, and the retry button is not crammed on one side.

Resolved Issue with Error Message Styling in Chat Window

---

extensions/vscode/src/util/ideUtils.ts

I added logging to see why only the SyntaxError: invalid syntax was being printed
`getTerminalContents called with commands: 1
extensionHostProcess.js:63105
Initial clipboard contents saved.
extensionHostProcess.js:63105
Selecting the last 1 commands from the terminal.
extensionHostProcess.js:63105
Copying selected text from terminal.
extensionHostProcess.js:63105
Terminal contents copied: nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule/extensions/vscode   main ±  cd ..
nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule
nathanan@Nathans-MacBook-Air  ~/Documents/working-dir/pearai-app/extensions/pearai-submodule   main ±  python3 extensions/vscode/pearai_tutorial.py
File …

Fixed terminal copying bug

---

extensions/vscode/src/extension.ts

On first run, copies all settings (including extensions and themes) and sync settings from .vscode to .pearai-dev for seamless ide transition although some settings might not apply automatically, will require restart

Issue #127 | Config migration from .vscode to .pearai-dev

---

extensions/vscode/src/extension.ts

Sorry for the sudden PR and not creating an Issue. I want to fix this quickly as it is blocking my development.
- Follow-up: https://github.com/trypear/pearai-submodule/pull/52
Check if `source` directory exists before migration of extensions (copying `.vscode/extensions`)
This avoids a crash on migration for users who don't have VS Code installed, and for developers (somehow my `pearai-app` build on Docker does not create the `~/.vscode` dir but the `~/.vscode-oss-dev` dir, which probably causes the same error).
| Before | After |
| --- | --- |
| <img src="https://github.com/trypear/pearai-submodule/assets/34566290/4a2422a0-32b2-45f3-b26e-9fdf259896a8" > | <img src="https://github.com/trypear/pearai-submodule/assets/34566290/e031692d-f9df-4fbc-8e0e-7bc926e2c14d"> |
So, where is `preview` …

Check if source dir exists before migration of extensions

---

.vscode/tasks.json

This change fixes the way vscode will run the debugger depending on the environment os.

Fix issues with debugging on Windows

---

gui/src/components/Layout.tsx
gui/src/index.css

Just nits issue.
If the pane is too narrow, the content on e.g. Onboarding page sticks over down from the container because the container's height is fixed.
Just replace `height` with `min-height` and it should fix this.
| Before | After |
| --- | --- |
|  <img src="https://github.com/trypear/pearai-submodule/assets/34566290/0b279b1a-23cc-49f0-85a5-ee50ca5250fd" > | <img src="https://github.com/trypear/pearai-submodule/assets/34566290/34926ba0-3286-4768-92ab-5ef3d9f5e5e0" > |
I didn't check the other pages, but we should probably do that before we merge.

Replace `height` css with `min-height` to prevent content from sticking over down

---

extensions/vscode/src/lang-server/codeLens.ts
extensions/vscode/src/webviewProtocol.ts

- Follow-up: https://github.com/trypear/pearai-submodule/pull/45
Updated codelens and fix Cmd/Ctrl replacing
Now we can correctly highlight the codes just by clicking `Highlight the function` above

Fix codelens for tutorial file

---

extensions/vscode/src/activation/activate.ts

- fixes: https://github.com/trypear/pearai-app/issues/131
Once the extension is activated, we'll open the pane up so users can jump right into the onboarding and the tutorial.
If we can skip the model selection process (or wait until after the tutorial is done), we can immediately open the tutorial file as well.
https://github.com/trypear/pearai-submodule/assets/34566290/47863d4d-39fe-4393-b06a-dd640bffcc5c

Open extension panel during first onboarding

---

.prettierrc

Made prettier use single-quote on both normal and jsx strings to avoid generating eslint warnings.
Issue link: https://github.com/trypear/pearai-app/issues/150

Made prettier use single-quote on both normal and jsx strings.

---

extensions/vscode/src/activation/activate.ts

#trypear/pearai-app#22
what this change does :
- when extension activates the very first time, move PearAI extension to auxiliary bar

feat: set default location PearAI extension to auxiliary bar

---

extensions/vscode/package.json
extensions/vscode/src/commands.ts

What changed -
- add shortcut display to pearai extension toolbar view.
- it will display CMD L on mac and ALT L on windows and linux (as linux users mostly would using a windows keyboard layout)
- the shortcut is hardcoded in title string, it will remain static for now until we figure out a way to change it.

feat: add big chat shortcut to view/title

---

extensions/vscode/src/extension.ts

.pearai is used for the actual packaged app instead of .pearai-dev
issue #127

Fixed config file from .pearai-dev to .pearai

---

gui/src/pages/modelconfig.tsx

- Changed "Add PearAI Server" button to "Start Coding 😎" for the server model panel. 
- Still working on the other asked for changes but wanted to send the PR for this first change.
---
Before:
After:
Maintainer edited: related to: https://github.com/trypear/pearai-app/issues/157

name change for PearAI server model panel

---

extensions/vscode/package.json

- added shortcut for view history - `cmd + o` and `ctrl + o`
- change alt to ctrl for resize chat.
- remove parenthesis from shortcut display of big chat.
rest all shortcuts are good for windows. they are set to ctrl.

view history shortcut

---

gui/src/components/dialogs/KeyboardShortcuts.tsx
gui/src/pages/models.tsx

- Related: https://github.com/trypear/pearai-app/issues/157
- Follow-up: https://github.com/trypear/pearai-submodule/pull/83, https://github.com/trypear/pearai-submodule/pull/86#discussion_r1667669662
Fix some grid style, though I have no idea why `grid` is used here... (we can just use `flex` more simpily)
| Before | After |
| --- | --- |
| **content overflown, and unnecessary y scroll bar** <br/><br/> ![image](https://github.com/trypear/pearai-submodule/assets/34566290/485beb1a-3d51-42f6-86e6-74a4027bb859) | ![image](https://github.com/trypear/pearai-submodule/assets/34566290/454bcbbb-5da9-4c99-a714-ad3d8ea64947) |
| Before | After |
| --- | --- |
| **content overflown, and unnecessary y scroll bar** <br/><br/> ![image](https://github.com/trypear/pearai-submodule/assets/34566290/afa4584d …

Fix more styles for config pages

---

extensions/vscode/src/extension/vscodeExtension.ts

problem : @ file tagging (context provider) is not picking filefolder changes
this pr fixes it using filewatcher. any filefolder change is immediately picked and context providers are refreshed.
---
- indexing got nothing to with context providers, both are separate.
- could also have done like this, but these events only happen if filefolder changes are done inside the vscode, it does not pick up the changes on the disk made by other applications.
```
vscode.workspace.onDidCreateFiles((event) => {
this.refreshContextProviders();
});
vscode.workspace.onDidDeleteFiles((event) => {
this.refreshContextProviders();
});
vscode.workspace.onDidRenameFiles((event) => {
this.refreshContextProviders();
});
```
- renaming a file means deleting and creating, so renaming fires both events in file …

fix file context provider stale

---

gui/src/pages/gui.tsx

current behaviour - opening any session loads at the top, even when switching between them.
this pr fixes that, sessions loads and scrolls to the bottom. 
used setTimeout with with delay 1ms to perform scrolling after 1st render cycle, for some reason 2-3 renders are happening whenever a session is loaded. this way scroll happens a little less janky.

open session at bottom

---

extensions/vscode/src/webviewProtocol.ts

As the title, however, I currently haven't found a method to reproduce the error. As a result, we might have to merge and then test in prod.
Add a third option when the user faces the 401 Error, allow redirect to login #195 issue in pearai-app

Added error handle for 401 Error, allow redirect to login auth url

---

gui/src/components/gui/StepContainer.tsx

- Enhanced the visibility of the "Continue Generation" button by making it always visible, rather than appearing on hover.
Closes https://github.com/trypear/pearai-app/issues/250

Make "Continue Generation" button more visible

---

gui/src/components/Layout.tsx

changed add selected to append selected as mentioned in issue #242
before:
after:

changed add selected to append selected

---

core/llm/autodetect.ts
core/llm/llms/PearAIServer.ts

Added image support with claude on pearai_server

---

extensions/vscode/media/welcome.md
gui/src/components/dialogs/KeyboardShortcuts.tsx
gui/src/hooks/useAuth.tsx
gui/src/pages/onboarding/Onboarding.tsx

Cleaned up welcome

---

core/config/default.ts
core/config/load.ts
core/index.d.ts
core/llm/index.ts
gui/src/components/modelSelection/ModelSelect.tsx

- Closes https://github.com/trypear/pearai-app/issues/271
What changed?
- adds 2 default models: gpt and claude supported by pear server
- disables deletion of default models
- addition of isDefault flag to model representation

feat: #271 add default gpt4o and claude models

---

gui/src/pages/AddNewModel/ConfigureProvider.tsx
gui/src/pages/AddNewModel/configs/providers.ts
gui/src/pages/onboarding/Onboarding.tsx

New Login pearai server

---

core/config/load.ts

Fixes this so that old verisons will have these

Added mandatory models

---

gui/src/components/ShortcutContainer.tsx

Adds check for the container size, and will render the arrows based on the check.
Closes [#301](https://github.com/trypear/pearai-app/issues/301)

Hide arrows when container expanded

---

gui/src/components/mainInput/ContinueInputBox.tsx

Closes https://github.com/trypear/pearai-app/issues/311
Changes from the default rainbow border (when chat is streaming to client) to the PearAI color.
https://github.com/user-attachments/assets/eaf2d798-f4aa-4f27-8e68-8602ce0507c5

Changed chat input border to PearAI colors

---

extensions/vscode/src/copySettings.ts

Closes [trypear/pearai-app#338](https://github.com/trypear/pearai-app/issues/338)
- Added the file that stores extensions disabled state (state.vscdb, state.vscdb.backup) to be copied from vscode settings
- Minor indentation fixes to copyVSCodeSettingsToPearAIDir function for readability

Add preservation of disabled extensions when copying
